[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/results.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
